# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ec29c6b31c7d87ef00fbf11a5aace31da4de01f7e70382d4849708ce73cf8e81f1d1827f94d67c0c7a7a79efe09a5cfe117877f57605ae2654b6a3779b95b7b8

test:
  secret_key_base: d94c3c6d480cac704e05fc8d20e6954c10c063991d75fe7c93c8d6033b9effbe33950498ed2b53a9f4c1f14d950109e3cfec3882cce61407df5e0fd2c76ae31c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
